# Generated by Django 5.1.6 on 2025-02-20 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('pol', models.CharField(blank=True, max_length=10)),
                ('has_parents', models.BooleanField(default=False)),
                ('livingplace', models.CharField(blank=True, max_length=255)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('birthplace', models.CharField(blank=True, max_length=255)),
                ('residence', models.CharField(blank=True, max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('trusted_person_phone', models.CharField(blank=True, max_length=20)),
                ('education', models.BooleanField(default=False)),
                ('education_level', models.CharField(blank=True, max_length=100)),
                ('specialty', models.CharField(blank=True, max_length=100)),
                ('has_working', models.BooleanField(default=False)),
                ('has_housing', models.BooleanField(default=False)),
                ('was_married', models.BooleanField(default=False)),
                ('has_children', models.BooleanField(default=False)),
                ('children_boys', models.CharField(blank=True, max_length=10)),
                ('children_girls', models.CharField(blank=True, max_length=10)),
                ('children_ages', models.CharField(blank=True, max_length=255)),
                ('height', models.IntegerField(default=170)),
                ('has_criminal_record', models.BooleanField(default=False)),
                ('has_bad_habits', models.CharField(blank=True, max_length=100)),
                ('performs_namaz', models.BooleanField(default=False)),
                ('clothing_preference', models.CharField(blank=True, max_length=100)),
                ('spouse_nationality_importance', models.BooleanField(default=False)),
                ('spouse_age_preference', models.IntegerField(default=30)),
                ('ok_with_divorced_spouse', models.BooleanField(default=False)),
                ('ok_with_spouse_children', models.BooleanField(default=False)),
                ('clothing_preferences', models.TextField(blank=True)),
                ('health', models.TextField(blank=True)),
                ('willing_to_relocate', models.BooleanField(default=False)),
                ('agree_to_be_second_wife', models.BooleanField(default=False)),
                ('plan_to_have_children', models.BooleanField(default=True)),
                ('health_status', models.TextField(blank=True)),
                ('additional_info', models.TextField(blank=True)),
                ('spouse_age', models.CharField(blank=True, max_length=10)),
                ('spouse_requirements', models.TextField(blank=True)),
                ('profile_completion_date', models.DateTimeField(blank=True, null=True)),
                ('consent_to_data_processing', models.BooleanField(default=False)),
                ('madhhab', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
